### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by ljfreelancer88** [hhvm/hsl#168] opened 2021-12-03 00:09 UTC
I followed the instruction here `https://docs.hhvm.com/hack/getting-started/starting-a-real-project` and used the code below but I got the following error `Fatal error: Call to undefined function square_vec() in /var/www/html/hacklang/src/index.hh on line 7` on both CLI and Web. It seems to be fine because I followed the documentation.

```php
<?hh
<<__EntryPoint>>
async function intro_examples_avoid_xss_main(): Awaitable<void> {
require_once(__DIR__.'/../vendor/autoload.hack');
  \Facebook\AutoloadMap\initialize();

  $squared = square_vec(vec[1, 2, 3, 4, 5]);
  foreach ($squared as $square) {
    printf("%d\n", $square);
  }
}
```

**Comment by lexidor** [comment] 2021-12-03 00:40
Well, this is not an issue with the Hack standard library, but I can help you with debugging it. I am closing the issue, but we can have a back and forth in the comment section even when the issue is closed.

The error you are describing happens when hhvm-autoload is unable to tell hhvm where square_vec is declared. There should be a file at `/var/www/html/hacklang/vendor/autoload.hack`. Does this file contain the text `square_vec`? If it does not, could you try running vendor/bin/hh-autoload? If it doesn't appear then, could you check the configuration in hhvm_autoload.json? The square_vec function must be declared in one of the directories you passed to the `"roots"` key (probably src).

**Closed by lexidor** 2021-12-03 00:40 UTC

**Comment by lexidor** [comment] 2021-12-03 01:10
I will be going offline for the day. Please @lexidor me if you have any questions or if the steps described above resolved the error. Messages which @ me send an email to me, which increases the chances I look at your response in a timely manner.

**Comment by ljfreelancer88** [comment] 2021-12-03 13:55
@lexidor, my bad, I didn't add `use namespace HH\Lib\Vec;`. What makes me confuse is, when I commented the `require_once(dirname(__DIR__) . '/vendor/autoload.hack')` and `\Facebook\AutoloadMap\initialize()`. The code still working.
So, when to add these `autoload.hack`?

```php
<<__EntryPoint>>
async function intro_examples_avoid_xss_main(): Awaitable<void> {
    //require_once(dirname(__DIR__) . '/vendor/autoload.hack');
    //\Facebook\AutoloadMap\initialize();
    $squared = square_vec(vec[1, 2, 3, 4, 5]);
    foreach ($squared as $square) {
        printf("%d\n", $square);
    }
}
  ```

**Comment by lexidor** [comment] 2021-12-03 14:33
@ljfreelancer88 if you are using the more advanced autoloader, the Facebook\AutoloadMap\initialize() will become a noop. The vendor/autoload.hack file is managed by the vendor/bin/hh-autoload script. You should never have to edit that file directly. When you call a function that hhvm does not yet know about, it looks in the dictionary passed to it by Facebook\AutoloadMap\Generated\map(). If the function is not in there, it uses the failure handler declared in hh_autoload.json as a final fallback. If that doesn't work, hhvm gives up and fatals on you. All functions that have an EntryPoint attribute MUST initialize the Facebook\AutoloadMap.

**Comment by ljfreelancer88** [comment] 2021-12-04 17:01
@lexidor Thank You. I hope there's a group chat, especially for the new "hacker" who wanted to dig-in the language. Thank you again.

**Comment by lexidor** [comment] 2021-12-04 17:16
@ljfreelancer88 The closest thing to a group chat would be https://hhvm.com/slack
There used to be an irc on freenode, but I believe that has been discontinued.
